name: Bug report
description: Help us improve frontend-collection
labels:
  - bug
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: 🐛 Current behavior
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔍 Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error

        You can attach screenshots by dragging and dropping, or selecting and pasting them in the text field.
    validations:
      required: true
  - type: input
    id: reproduction-links
    attributes:
      label: Live reproduction
      description: |
        A live example helps a lot! In case you have a running instance of frontend-collection which can be used to reproduce the issue, please provide it here.
      
      placeholder: https://codesandbox.io/...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 💭 Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Release version
      description: Which version of frontend-collection are you using?
      placeholder: e.g., frontend-collection 1.0.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g., macOS 13.1
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g., Firefox 108.0.1
